package eg.edu.alexu.csd.datastructure.mailServer.LogicClasses;

public enum SORTING {
	NEWEST,
	OLDEST,
	ASCENDING_IMPORTANCE,
	DESCENDING_IMPORTANCE,
	ASCENDING_SUBJECT,
	DESCENDING_SUBJECT,
	ASCENDING_SENDER,
	DESCENDING_SENDER,
	ASCENDING_N_ATTACH,
	DESCENDING_N_ATTACH
}
